### ISSUE TITLE
dnt is not ready yet for some new Deno stuff

### ISSUE THREAD

**Issue by lttr** [lttr/deno-shell-aliases#1]
```bash
❯ deno run -A _build.ts 1.0.5
[dnt] Transforming...
[dnt] Running npm install...

added 7 packages, and audited 8 packages in 3s

found 0 vulnerabilities
[dnt] Building project...
[dnt] Type checking ESM...
src/aliases.ts:81:36 - error TS2339: Property 'Command' does not exist on type 'typeof Deno'.

81   const process = new dntShim.Deno.Command(command, {
                                      ~~~~~~~
src/deps.ts:1:23 - error TS2307: Cannot find module '@std/path' or its corresponding type declarations.

1 export * as path from "@std/path";
                        ~~~~~~~~~~~
src/deps.ts:2:45 - error TS2307: Cannot find module '@std/assert' or its corresponding type declarations.

2 export { assertEquals, assertRejects } from "@std/assert";
                                              ~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Had 3 diagnostics.
          throw new Error(`Had ${diagnostics.length} diagnostics.`);
                ^
    at getProgramAndMaybeTypeCheck (https://deno.land/x/dnt@0.40.0/mod.ts:457:17)
    at build (https://deno.land/x/dnt@0.40.0/mod.ts:345:17)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async file:///home/lukas/code/deno-shell-aliases/_build.ts:12:1
```

**Comment by lttr** [comment]
Therefore unable to publish newer versions to NPM.

**Comment by lttr** [comment]
https://github.com/denoland/node_shims/blob/main/packages/shim-deno/PROGRESS.md
